### ISSUE TITLE
`maybe_localize()` is called twice

### ISSUE THREAD

**Issue by schlessera** [brightnucleus/dependencies#4]
When automatic enqueueing and manual enqueueing are combined, `maybe_localize()` is called twice and produce duplicate results.

**Comment by TimothyBJacobs** [comment]
AFAICT `DependencyManager::enqueue_dependency` is only called by `DependencyManager::enqueue_internal_handle`. The issue is both functions call `maybe_localize()`. Seems like it could be solved by removing either duplicate `maybe_localize()` call.
